boostcampwm2023/web01-GitChallenge

.husky/commit-msg
close #27 
- commit msg 훅에서 브랜치 이름에 이슈 번호가 없을 때 커밋 메시지에 브랜치 이름이 추가되는 문제 해결
- 브랜치 이름에 이슈 번호가 없으면, 커밋 메시지에 브랜치 이름이 추가되지 않는다.
- 버그 수정 TASK인데 "개발 환경을 세팅한다 에픽 > 공통 개발 환경 세팅 스토리" 에 포함시켰습니다. 괜찮은가요.?
- 제 환경에서만 잘 동작할 수도 있어서 한 번 테스트 해주실 수 있을까요?
=> [공통] fix#27 브랜치 이름에 이슈 번호가 없을 때 커밋 메시지에 브랜치 이름이 추가되는 문제

.yarn/sdks/eslint/bin/eslint.js, .yarn/sdks/eslint/lib/api.js, .yarn/sdks/eslint/lib/unsupported-api.js, .yarn/sdks/eslint/package.json, packages/backend/package.json, yarn.lock
close #44 
yarn dlx @yarnpkg/sdks vscode 명령 실행
./package.json과 backend 폴더 내의 ./package.json 파일의 eslint버전을 일치시키고 yarn install실행
* 이전 PR 코드에서 vscode 설정이 안 되어 있었다.
* 그리고 새로운 issue와 PR을 생성하는 것으로 작업 흐름을 정했다!
* 백엔드 코드에 대해 vscode에서 eslint가 정상적으로 작동
* 작업 흐름 관련 궁금증 해결됨!
=> [BE] config#44 개발환경 세팅 vscode 추가 작업

.yarn/sdks/eslint/bin/eslint.js, .yarn/sdks/eslint/lib/api.js, .yarn/sdks/eslint/lib/unsupported-api.js, .yarn/sdks/eslint/package.json, packages/frontend/.eslintrc.json
close #47 
- ESLint sort-imports, import/order 규칙 설정 및 적용
- sort-imports
- 대소문자 구분 없이 정렬 O
- import 문 정렬 무시 (import/order 규칙과 충돌해서 무시로 변경)
- 멤버 정렬 O
- ex. `import { c, b, a } from "~"` > `import { a, b, c } from "~"`
- 멤버 갯수(?)에 따라 none, all, multiple, single 순으로 정렬 (자세한 설명은 [여기](https://eslint.org/docs/latest/rules/sort-imports#options)에)
- 그룹 내에서 개행 불가능
- import/order
- builtin, external, internal, parent, sibling, index 그룹 모듈 순으로 정렬
- 모듈 그룹간 개행을 항상 추가
- .yarn 경로 내 모듈을 external로 설정   
- ESLint require-default-props, no-use-before-define 규칙 off
- ESLint vscode sdks 설치
- sort-imports랑 import/order 규칙이 충돌할 때가 있다는데, 현재 import 문이 많지 않아서 충돌하는 규칙을 모르겠습니다.. 나중에 충돌 발생하면 규칙 고쳐야 할 수도 있습니다!
- `import from "~"`와 같은 [side effect import문](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Referenc …
=> [FE] config#47 ESLint sort-imports, import/order 규칙 설정 및 적용

packages/frontend/src/components/common/Button/Button.css.ts, packages/frontend/src/components/common/Button/Button.tsx, packages/frontend/src/components/common/index.ts, packages/frontend/src/styles/color.ts, packages/frontend/src/styles/global.css, packages/frontend/src/utils/__tests__/classnames.spec.ts, packages/frontend/src/utils/__tests__/typeGuard.spec.ts, packages/frontend/src/utils/classnames.ts, packages/frontend/src/utils/typeGuard.ts
close #43
- Button 컴포넌트 구현
- Storybook + vanilla extract 에러는 나중에 해결하겠습니다..
- vanilla extract를 사용해서 색상별로 variant를 선언한다.
- disabled 된 Button은 hover해도 스타일 변화가 없다.
- vanilla extract는 클래스 이름으로 스타일링하다보니 클래스 이름을 쉽게 조합하는 [classnames 패키지](https://github.com/JedWatson/classnames)가 생각났습니다! 그런데 아직 많은 기능이 필요한 것 같지는 않아서 작은 유틸 함수 하나 만들어봤습니다. 패키지 설치보다는 기능 하나씩 추가하는 것도 괜찮은 것 같은데 어떻게 생각하시나요?
- 스타일링 잘못된 곳이 있다면 알려주세요!
- 버튼에 `width` 값이 없어서 `border` 유무에 따라 버튼 `width` 가 달라집니다..! 그래서 `border: "1px solid transparent",`으로 동일한 `width` 가 되도록 해봤는데 괜찮은가요?
cf. [테스트용 코드](https://www.notion.so/Button-bcf4a703907d4c1780a360f3fe890bb7)
=> [FE] feat#43 Button 컴포넌트

packages/frontend/src/components/common/Badge/Badge.css.ts, packages/frontend/src/components/common/Badge/Badge.tsx, packages/frontend/src/components/common/Badge/BadgeGroup.tsx, packages/frontend/src/components/common/Badge/index.ts, packages/frontend/src/components/common/Button/Button.tsx, packages/frontend/src/components/common/Button/index.ts, packages/frontend/src/components/common/index.ts, packages/frontend/src/utils/types.ts, packages/frontend/tsconfig.json
close #42 
- Badge 컴포넌트 구현
- BadgeGroup 컴포넌트 구현
- 절대경로 해제
- 컴포넌트별 index.ts 파일로 컴포넌트 export 하도록 변경
- Button 컴포넌트에 style import에 styles 프리픽스 적용
- 없습니다!
- BadgeGroup으로 핵심 명령어 목록을 보여줄 수 있다.
- BadgeGroup에서 variant list(색상 리스트)를 array로 관리하는데 더 좋은 방법이 있을까 싶어요!
cf. [테스트 코드](https://bow-snail-89d.notion.site/Badge-BadgeGroup-7c9534ec6476434290e3ae63484490a9?pvs=4)
=> [FE] feat#42 Badge 컴포넌트

packages/frontend/src/design-system/components/common/Footer/Footer.css.ts, packages/frontend/src/design-system/components/common/Footer/Footer.tsx, packages/frontend/src/design-system/components/common/Footer/index.ts, packages/frontend/src/design-system/components/common/index.ts
close #63
- Footer 컴포넌트 구현
- 깃허브 아이콘 클릭 시 GitChallenge 레포 페이지 연결
- body 태그에 적용된 flex 없애고 테스트 했습니다!
- 테스트 커밋([888bec2](https://github.com/boostcampwm2023/web01-GitChallenge/pull/80/commits/888bec2ec8f52760bc5938613b07f00059e2da29)) 없애고 머지해야 합니다!
- 디자인 명세에 맞게 스타일링한다.
- 깃허브 아이콘으로 GitChallenge 레포로 이동할 수 있다.
- Contact: Issues로 MergeMasters에게 연락할 수 있다.(?)
- Contact에 임시로 GitChallenge 레포 이슈 페이지 연결했습니다. 다른 걸로 바꿀까요?
=> [FE] feat#63 Footer 컴포넌트

packages/backend/.gitignore, packages/backend/package.json, packages/backend/src/app.module.ts, packages/backend/src/containers/containers.module.ts, packages/backend/src/containers/containers.service.spec.ts, packages/backend/src/containers/containers.service.ts, packages/backend/src/quizzes/dto/command-request.dto.ts, packages/backend/src/quizzes/dto/command-response.dto.ts, packages/backend/src/quizzes/quizzes.controller.ts, packages/backend/src/quizzes/quizzes.module.ts, packages/backend/src/quizzes/quizzes.service.ts, yarn.lock
close #7 
- 현재 컨테이너 정보를 동적으로 알 수 없기 때문에(세션이나 DB 없음) 일단 'testContainer'라는 컨테이너에 고정으로 명령이 갑니다.
- 현재 컨테이너는 commit 1개, add된 파일 1개, untracked된 파일 1개를 가지고 있습니다(사진 첨부)
- commit을 위해 --global설정도 해 두었습니다(user: MergeMaster, email: mergemaster@gitchallenge.com)
- 현재 API가 붙어 있지 않고 코드만 있습니다. 수동으로 테스트 했으며, DB가 붙고 세션 분간이 되어야 이 코드를 사용할 수 있습니다.
- e2e 흐름
1. 명령어 요청이 오면 세션을 확인
2. 세션이 없거나 세션에 할당된 컨테이너가 없다면(죽었다면) 컨테이너 생성
1. docker run
2. 컨테이너 서버 로컬(~/quizzes/${quizId}) 에서 문제 컨테이너 내부(/${user}/quiz)로 cp
3. 이제 컨테이너는 무조건 있으니 명령 실행
4. 결과 리턴
* 흐름에서 나타냈듯, 당장 동작을 위해서 컨테이너 서버 로컬 ~/quizzes/ 안에 문제별로 문제 상황을 꾸며 놓으면 됩니다.아마 이게 최선일 듯 싶네요?
* git log
* git status
* git branch
* MergeMaster 최고
- Slack에도 간단하게 공지했지만, 현재 success/fail 여부는 stdout, stderr로 구분하고 있습니다
- 이 구분이 우리의 인식과 조금 다른 경우가 있습니다. 하지만 어차피 실행된 결과 문자열을 반환하기 때문에 당장 동작에는 …
=> [BE] feat#7 컨테이너 생성/컨테이너 명령 실행

packages/frontend/src/constants/index.ts, packages/frontend/src/design-system/components/common/Button/Button.css.ts, packages/frontend/src/design-system/components/common/Button/Button.tsx, packages/frontend/src/design-system/components/common/IconButton/IconButton.css.ts, packages/frontend/src/design-system/components/common/IconButton/IconButton.tsx, packages/frontend/src/design-system/components/common/IconButton/index.ts, packages/frontend/src/design-system/components/common/Modal/Modal.css.ts, packages/frontend/src/design-system/components/common/Modal/Modal.tsx, packages/frontend/src/design-system/components/common/Modal/index.ts, packages/frontend/src/design-system/components/common/index.ts, packages/frontend/src/design-system/tokens/utils.css.ts, packages/frontend/src/hooks/useModal.ts, packages/frontend/src/pages/_document.tsx, packages/frontend/src/utils/event.ts
close #41 
- IconButton 컴포넌트 구현
- React createPortal로 모달 컴포넌트 구현
- 백드롭 클릭 시 모달 꺼지도록 구현 + 모달 박스 클릭시 이벤트 버블링 방지로 util 함수 구현 후 적용
- esc 키 눌렀을 때 모달 꺼지도록 구현
- 모달이 켜져있을 때 스크롤 안되도록 처리
커서가... 보이는줄 알았는데 안보이네요...?!
위 내용 모두 테스트 완료했습니다!
마운트 되지 않았을 때 모달에서 doument를 찾아
`document is not defined` 에러가 발생했습니다.(하이드레이션 관련 issue) 
=> `mounted` useState변수로 플래그를 걸어서 해결했습니다! 관련 커밋 49393d2e41b4092b4fe892cb52a792dcbca4e43b
https://univdev.page/posts/nextjs-portal/
- 모달 외부(백드롭)를 클릭했을 때 모달이 꺼진다.
- esc 키를 눌렀을 때 모달이 꺼진다.
- 모달창이 켜졌을 때 외부 스크롤이 방지된다.
- 모달을 커스텀해서 사용할 수 있다.
- esc 키 이벤트와 스크롤 방지는 훅으로 분리할 수 있을 것 같아서 useModal hook으로 분리해봤는데 어떤가요?
- Portal을 컴포넌트화할 수 있었는데, 저희 프로젝트 상황에는 모달에만 적용될 것 같아 모달에 바로 적용시켰습니다. 따로 안만들어도 괜찮은지 유현님 생각이 궁금합니다!
테스트용 코드 마지막 커밋에 포함시켜뒀어요! 머지되기 전에 날리고 머지할게요~! layout 페이지로 들어가시면 됩니당🙌
=> [FE] feat#41 Modal 컴포넌트

packages/backend/package.json, packages/backend/src/app.controller.ts, packages/backend/src/main.ts, packages/backend/src/quizzes/dto/command-request.dto.ts, packages/backend/src/quizzes/dto/command-response.dto.ts, packages/backend/src/quizzes/dto/quiz.dto.ts, packages/backend/src/quizzes/dto/quizzes.dto.ts, packages/backend/src/quizzes/quizzes.controller.ts, yarn.lock
close #59 
- swagger 모듈 설치 (@nestjs/swagger)
- swagger에 잡히기 때문에 기존 '/' 요청 비활성화(Hello World 이제 안 나옴)
- 현재 모든 DTO, API에 대해 설명 작성
- 실행하면서 진짜 똑같은지 손으로 몇 번 테스트도 해 봤어요...
- POST 시 세션이 생성돼서 그런지 아니면 기본값이 201인지 모르지만 nestjs가 201을 응답하는데, 우리의 동작 상 200 OK가 더 정확하다고 생각해서 (혹은 세션 생성 시 201로 분기 처리?) 일단 200으로 명시했습니다. 이 부분 적극적으로 의견 주셔도 좋아요.
*참고로 /api 루트로 swagger 접속 가능합니다.
이런 느낌입니다.
- swagger 처음 해 봐서 이렇게 데코레이터 주렁주렁 다는게 맞는지 모르겠는데, 일단 GPT는 괜찮다고 합니다.
- swagger 접속 가능
- swagger에 DTO 묘사
- swagger에 API 묘사
- 앞으로는 API 만들면 swagger까지 붙여서 push 하는거 어떨까요? 너무 당연한 말인가요?
=> [BE] feat#59 swagger 최초 도입

packages/backend/src/containers/containers.service.ts, packages/backend/src/quizzes/quizzes.controller.ts, packages/backend/src/session/schema/session.schema.ts, packages/backend/src/session/session.service.ts
close #68
- 컨테이너 존재 여부 검증 로직 작성
- 세션 ID와 문제 번호로 컨테이너 ID 조회 로직 수정
- 스키마 문제 ID를 number로 수정
- 기존 `살려야함` 코드 살리기
- 기타 로그 작성
- 로거 슬슬 도입해야 할까요...?
- 세션이 없으면 세션이 DB에 생성됨
- 컨테이너가 없으면 해당 문제의 컨테이너가 컨테이너 서버에 생성됨, DB에 해당 문제 삽입
- 이후 해당 컨테이너에 POST body로 전달된 command 실행
- 결과 리턴
- 없습니다!
=> [BE] feat#68 세션&문제 별 컨테이너 ID 조회(없으면 생성) 한 뒤 해당 컨테이너에 command 실행 구현

packages/backend/src/quizzes/quizzes.controller.ts, packages/backend/src/session/session.service.ts
[#71]
close #71 
- session에 유저 입력 기록을 추가한다.
없습니다!
- user가 comman를 입력했을때 session에 기록된다.
- 바로 이어서 문제 초기화 delete 바로 구현 가능할 것 같아요
=> [BE] feat#71 user command 기록 추가

packages/frontend/src/components/terminal/CommandInput.tsx, packages/frontend/src/components/terminal/Prompt.tsx, packages/frontend/src/components/terminal/Terminal.css.ts, packages/frontend/src/components/terminal/Terminal.tsx, packages/frontend/src/components/terminal/TerminalContent.tsx, packages/frontend/src/components/terminal/index.ts, packages/frontend/src/constants/index.ts, packages/frontend/src/design-system/components/common/Modal/Modal.tsx, packages/frontend/src/types/terminalType.ts, packages/frontend/src/utils/scroll.ts
close #69
- Terminal 구현
- body 태그 내 flex 스타일 없애고 테스트했습니다!
- Prompt 컴포넌트를 제거하고 `::before` 가상 선택자로 '$'를 추가해 봤는데 아래 처럼 커서가 $ 이전에 위치합니다. 나중에 Prompt 컴포넌트 제거를 다시 한 번 시도해 보겠습니다..!
- 테스트 커밋([7ce18c9](https://github.com/boostcampwm2023/web01-GitChallenge/pull/92/commits/7ce18c91237bde737add63e0eacc97e49db223c2))이 포함되어 있습니다. 머지 전에 제거해야 합니다!
- Terminal 에 입력할 수 있다.
- Terminal 에 입력값과 응답값이 기록된다.
- Terminal 내용이 세로 영역보다 길어지면 스크롤 처리된다.
- 없습니다!
=> [FE] feat#69 Terminal 컴포넌트

.github/workflows/backend-deploy.yml, packages/backend/package.json, packages/backend/src/app.module.ts, packages/backend/src/common/logging.interceptor.ts, packages/backend/src/containers/containers.service.ts, packages/backend/src/quizzes/quizzes.controller.ts, packages/backend/src/session/session.service.ts, yarn.lock
close #100 
- winston 로거 도입
- winston logger app.modules.ts 에 선언
- winston logger 규칙 선언
- winston Daily Rotate 도입
- console.log 로거로 대체
- quizzes.controller로 들어오는 모든 요청(ex: GET /api/v1/quizzes from sessionid: asdf) 을 로깅하는 함수 작성
- 배포 시 컨테이너 안에 저장되는 로그를 밖으로 빼 오기 위해 volume mounting 진행
- 로컬 디렉토리: ~/backend-logs/
- 컨테이너 디렉토리: /app/packages/backend/logs/
- 개발 디렉토리: packages/backend/logs/
로그 이런 식으로 쌓여요
- 아마 병렬적으로 작업했는데 백퍼 conflict 납니다... 하지만 우리는 🔥 M E R G E M A S T E R 🔥
- winston 로거 잘 작동
- 배포된 서버에서 volume mounting 및 로그 수집
- no more console.log!!!
- 없습니다!
=> [BE] feat#100 winston 로거 도입

packages/backend/src/containers/containers.service.ts, packages/backend/src/quizzes/quizzes.controller.ts, packages/backend/src/session/session.service.ts
close #11 
- DELETE /quizzes/:id/command 컨트롤러에 추가
- container service 컨테이너 삭제 로직 구현
- session service 세션에 기록과 컨테이너 id 삭제하는 로직 구현
- 이후 docker orphan prune 명령을 시행 할 시기를 정해요
- swagger 동작 명시 여부..?
- DELETE /quizzes/:id/command 요청시 세션의 기록과 컨테이너id, 실제 컨테이너가 종료된다
=> [BE] feat#11 문제 초기화시 기록과 컨테이너 삭제 기능 구현

packages/frontend/src/components/quiz/QuizContent/QuizContent.css.ts, packages/frontend/src/components/quiz/QuizLocation/QuizLocation.css.ts, packages/frontend/src/components/terminal/Terminal.css.ts, packages/frontend/src/design-system/components/common/Button/Button.css.ts, packages/frontend/src/design-system/components/common/Layout/Layout.tsx, packages/frontend/src/design-system/components/common/SideBar/SideBar.tsx, packages/frontend/src/design-system/styles/global.css, packages/frontend/src/mocks/apis/data/quizContentData.ts, packages/frontend/src/pages/demo.css.ts, packages/frontend/src/pages/demo.tsx
close #75 
- 3주차 데모용 퀴즈 페이지 스타일링
- 아래는 모니터에서 촬영했습니다.
- 아래는 노트북에서 보이는 화면입니다.
- Terminal 컴포넌트에서 터미널 내용이 변경될 때마다 `scrollIntoView`를 하고 있는데, 페이지에서 보니까 동작이 부자연스러워서 빼는 게 좋아 보입니다..!
- 제 모니터에서는 문제 제출하기 버튼이 짤리는데, 노트북에서는 터미널부터 짤립니다..!
- base layout 스타일에 `height: 100vh` 때문에 아래처럼 레이아웃이 깨지는 문제가 있습니다. 임시로 `minHeight: 100vh`로 변경했는데, 이렇게 하면 사이드바에는 고정된 `height`값이 없어 스크롤 처리가 안 됩니다..어떻게 해결하면 좋을까요🥹
- 디자인 명세에 맞게 스타일링한다. 
- /demo 페이지로 만든다.
- 이슈 상황과 동일합니다.
=> [FE] style#75 데모용 퀴즈 페이지 스타일링

packages/frontend/src/apis/quizzes.ts, packages/frontend/src/components/demo/Demo.tsx, packages/frontend/src/pages/quizzes/[id].tsx, packages/frontend/src/types/quiz.ts
close #118 
- 페어 프로그래밍 했읍니당 ✌🏻
- CSR로 우선 구현 후 getStaticPath 사용해 SSG 렌더링으로 변경 후 비교
없습니다!
- SSG로 퀴즈 페이지가 빌드 시에 만들어진다.
없습니다!
=> [FE] feat#118 문제 페이지를 SSG 방식으로 렌더링한다.

packages/frontend/src/components/quiz/CommandAccordion/CommandAccordion.tsx, packages/frontend/src/components/quiz/QuizContent/QuizContent.css.ts, packages/frontend/src/design-system/components/common/Accordion/Accordion.tsx, packages/frontend/src/design-system/components/common/Accordion/AccordionContextProvider.tsx, packages/frontend/src/design-system/components/common/SideBar/nav.ts, packages/frontend/src/pages/quizzes/[id].tsx
close #121
- 목차 데이터 최신화 및 오타 수정
- 문제 페이지 스타일링 수정
- 스타일링 수정 
- 미디어쿼리 1920 ~ 2559 시 핵심 명령어와 모범 답안 확인하기 충돌
- 핵심 명령어가 아코디언 width보다 커질 때 뱃지 글자 줄바꿈
|AS-IS|TO-BE|
|-|-|
|<img width="1331" alt="스크린샷 2023-11-24 오전 8 48 18" src="https://github.com/boostcampwm2023/web01-GitChallenge/assets/96400112/54ca8c30-0a67-4331-b243-06851b2b0fa1">|<img width="1342" alt="스크린샷 2023-11-24 오전 8 49 58" src="https://github.com/boostcampwm2023/web01-GitChallenge/assets/96400112/5c0066c8-8331-49ac-a4b6-47879295122a">|
- 목차 데이터는 임시로 한글화했습니다!
- 목차 데이터는 한글이지만, 문제 조회 API 에서는 영어이기 때문에 문제 페이지에서 "Git Advanced > git cherry-pick" 식으로 나옵니다.
- 목차 데이터를 서버 데이터와 동기화한다.
- 스타일링 깨지는 곳을 수정한다.
- 없습니다!
=> [FE] hotfix#121 목차 데이터 최신화, 문제 페이지 스타일링

packages/backend/src/containers/containers.service.ts
[#123]
close #123 
- docker container는 네트워크가 불능해야한다
```bash
root@****:~# docker exec -it f6a191153cc4 /bin/sh
/ # ping www.google.com
^C
root@****:~# docker inspect f6a191153cc4
#...
"Networks": {
"none": {
"IPAMConfig": null,
"Links": null,
"Aliases": null,
"NetworkID": "****",
"EndpointID": "****",
"Gateway": "",
"IPAddress": "",
"IPPrefixLen": 0,
"IPv6Gateway": "",
"GlobalIPv6Address": "",
"GlobalIPv6PrefixLen": 0,
"MacAddress": "",
"DriverOpts": null
}
}
#...
```
- 피어세션에서 데모 링크 보내줬을때 누가 바로 clone 명령 시도하는거 보고 도입했습니다
- docker container는 네트워크가 불능해야한다
도커 명령어로 네트워크 차단했습니다.
알파인 리눅스 내부의 설정을 건드릴까 하다가, 도커로 설정하는게 관리측면에서 이점을 가질 것 같아 이렇게 해결했는데 괜찮을까요?
=> [BE] 제공되는 터미널 환경에서는 네트워크가 불능해야한다 

packages/backend/src/common/command.guard.ts, packages/backend/src/quizzes/quizzes.controller.ts
close #167 
- [';', '>', '|', '<'] block
- 디렉토리 common으로 이동
- ';', '>', '|', '<' 가 포함된 명령은 차단된다
- 백엔드 방어로직이 보강되기 전까지 입력에서 차단하는게 좋다고 생각합니다
=> [BE]feat#167 파이프, 세미콜론, 부등호 등의 커맨드 체이닝을 방지한다

packages/backend/src/quizzes/quizzes.controller.ts, packages/backend/src/session/schema/session.schema.ts, packages/backend/src/session/session.service.ts
[#172]
close #172 
- session log 스키마 변경
- 최긘 log 조회 함수 변경
- log 삽입 함수 변경
- merge하면 바로 데이터베이스 날려주세요!
- 새로운 스키마에 맞는 log가 잘 적용된다
=> [BE] feat#172 session log 스키마 수정

packages/frontend/src/components/editor/Editor.tsx, packages/frontend/src/components/editor/__tests__/editor.spec.tsx
close #186 
- 편집기 라인 모드에서
- 지원하지 않는 명령어 입력 시 에러 메시지 표시 후 명령 모드로 전환
- 빈 값 입력 시 명령 모드로 전환 (vi 테스트하다 발견한 기능이라 추가로 구현했습니다)
- 편집기 테스트 코드 작성
- 편집기 일부 리팩토링
**테스트 결과**
**라인 모드에서 지원하지 않은 명령어를 입력**
| vi 실제 동작 | Editor 동작 |
|-|-|
|![vi not command](https://github.com/boostcampwm2023/web01-GitChallenge/assets/96400112/efa03238-45c6-4886-8972-5e0d45d89d0a)|![editor line not eidtor command](https://github.com/boostcampwm2023/web01-GitChallenge/assets/96400112/177ad68a-5c08-42ef-81d4-a39dd75f709f)|
**라인 모드에서 빈 값 입력 시 명령 모드로 전환**
| vi 실제 동작 | Editor 동작 |
|-|-|
|![vi empty command](https://github.com/boostcampwm2023/web01-GitChallenge/assets/96400112/99659f0d-68fd-4be0-8350-200adf28f83b)|![editor empty command](https://github.com/boostcampwm2023/web01-GitChallenge/assets/96400112/103dac7f-d2f2-4c83-8d36-f7 …
=> [FE] feat#186 편집기 라인 모드에서 지원하지 않는 명령어 입력 처리

packages/frontend/.eslintrc.json, packages/frontend/package.json, packages/frontend/src/components/editor/__tests__/editor.spec.tsx, yarn.lock
close #189
- eslint-plugin-testing-library 추가
- 테스트 파일에만 testing-library/react 룰 적용
- Editor 테스트 코드 eslint 에러 해결 (`document.activeElement` 빼고는 잘 작성했나봐요! 고칠 게 많이 없었습니다ㅎㅎ)
**테스트 결과**
**ESLint 동작 확인**
- eslint-plugin-testing-library 를 적용한다.
- 없습니다!
=> [FE] feat#189 eslint-plugin-testing-library 설정/적용

packages/backend/src/quiz-wizard/quiz-wizard.service.ts, packages/backend/test/app.e2e-spec.ts
close #158 
- 8번 문제 채점 테스트 코드 작성
- 8번 문제 채점 로직 작성
- 계획 때는 확실히 하려고 초기 4개를 검사하자고 했는데, 초기 4개부터 내려오는 로직은 매끄럽지 않기 때문에(자식부터 올라가는 포인터가 있는 구조) 커밋 메시지를 기준으로 찾아서 커밋 3개 올라가면서 검증합니다.
- 8번 문제 채점 가능
- 모든 테스트 통과
- 없습니다!
=> [BE] feat#158 8번 문제 채점 로직 구현

packages/backend/src/quiz-wizard/magic.ts, packages/backend/src/quiz-wizard/quiz-wizard.service.ts, packages/backend/test/app.e2e-spec.ts
close #159 
- 9번 문제 테스트 케이스 설계
- 해결책이 간단하다 보니 머리의 한계로 케이스가 좀 약한 것 같아요
- 9번 문제 채점 로직 구현
- 4번 문제 더 정확한 버전으로 수정
- 실제 4번 문제 정확한 버전 컨테이너에도 반영
- 없습니다!
- 9번 문제 채점 가능
- 없습니다!
=> [BE] feat#159 9번 문제 채점 로직 구현

packages/frontend/src/components/terminal/CommandInput.tsx, packages/frontend/src/components/terminal/Terminal.css.ts
close #139
- Terminal에 복사/붙여넣을 때
- 기본 동작을 막고, 플레인 텍스트로 삽입
- 가로 스크롤 막기
- 커서가 있는 곳으로 스크롤하기 (CSS로 해결)
**복사/붙여넣기 버그**
|AS-IS|TO-BE|
|-|-|
|![terminal paste asis](https://github.com/boostcampwm2023/web01-GitChallenge/assets/96400112/1a93c241-0a22-4ce5-b50f-60d28ffd2da1)|![terminal paste tobe](https://github.com/boostcampwm2023/web01-GitChallenge/assets/96400112/ca4a283b-03c7-46ef-baba-25ae2e58dcf3)|
**붙여넣기 시 커서가 있는 곳으로 스크롤하기**
|AS-IS|TO-BE|
|-|-|
|![terminal cursor asis](https://github.com/boostcampwm2023/web01-GitChallenge/assets/96400112/e44379fd-4752-4ac6-b4a2-91fa7c44b267)|![terminal cursor tobe](https://github.com/boostcampwm2023/web01-GitChallenge/assets/96400112/d71a8eb5-6cc6-4e47-ab7a-3d01f6adb346)|
**붙여넣기 시 가로 스크롤 막기**
|AS-IS|TO-BE|
|-|-|
|![terminal break …
=> [FE] fix#139 Terminal 붙여넣기 버그

packages/frontend/src/apis/quiz.ts, packages/frontend/src/components/terminal/Terminal.tsx, packages/frontend/src/mocks/apis/quizHandlers.ts, packages/frontend/src/pages/quizzes/[id].page.tsx, packages/frontend/src/pages/quizzes/quiz.css.ts
close #10
- 문제 페이지에 초기화 버튼 추가
- 초기화 API 모킹
- **에러 테스트를 위해 1번 문제는 500 응답, 그 외에는 200 응답**으로 설정했습니다.
- 초기화 API 연결
- 퀴즈 페이지 이동 시 터미널 입력값이 초기화되지 않는 문제 해결
**초기화 성공**
**초기화 실패 (모킹 API 환경에서 테스트했습니다)**
**퀴즈 페이지 이동 시 터미널 입력값 초기**
- 피그마 디자인을 보면 아래와 같이 되어있지만, Undo 기능은 나중에 추가될 것 같아서 Undo 자리에 Reset 버튼을 뒀습니다.
- 퀴즈 페이지 스타일링이 많이 변경될 것 같아서 임시로 초기화 버튼 스타일 코드도 demo.css.ts에 작성했습니다. 
- API 성공/실패 관련 코드는 나중에 API 인터셉터나 훅을 만들 것 같아서 대충 작성했습니다..😅
- 초기화 성공 시
- 터미널을 초기화한다.
- 터미널에 포커싱한다.
- 토스트 메시지로 사용자에게 안내한다.
- 초기화 실패 시 토스트 메시지로 사용자에게 안내한다.
- ~~초기화 성공 시 터미널과 편집기를 어떻게 할지 고민입니다..!~~ [회의](https://www.notion.so/11-30-cbf2eacb0323427fa9414e95d436c822?pvs=4#94392e842323416badb0e7afe46284e4)로 결정했습니다!
- `Button` 컴포넌트 레이아웃을 위해 div 태그로 감쌌는데, `Button` 컴포넌트에 `props.className`을 추가해서 바로 레이아웃할 수 있도록 할까 고민 중입니다!
=> [FE] feat#10 문제 초기화 API 연결 (작업 완료!)

packages/frontend/src/components/quiz/QuizGuide/QuizGuide.css.ts, packages/frontend/src/components/terminal/Terminal.css.ts, packages/frontend/src/components/terminal/Terminal.tsx, packages/frontend/src/design-system/styles/global.css, packages/frontend/src/design-system/styles/reset.css, packages/frontend/src/hooks/useResizableSplitView.ts, packages/frontend/src/pages/quizzes/[id].page.tsx, packages/frontend/src/pages/quizzes/quiz.css.ts
close #120 
- useResizableSplitView Hook 구현
- 헤드리스 느낌으로 구현해봤는데 사실 가장 큰 이유는 퀴즈 페이지의 상단 부분과 사이즈 조절 바, 그리고 터미널을 페이지단에서 핸들링해야해서 페이지 단 로직이 너무 커지는 것 같아 분리하게 되었습니다!
- 퀴즈 페이지에 적용
- 초반에 스플릿 바에 마우스 다운을 할 때, 높이가 잠깐 뒤틀리는데 왜 초반에만 뒤틀리는지 디버깅해보았는데 해결을 하지 못했습니다... 😭
- 그 다음부터는 커서가 잘 잡혀요
- 이슈 사항이라고는 뭐하지만 데모 페이지 삭제하고 레이아웃 손 봐야할 것 같습니다! 터미널 리사이징 구현 도중에 해당 태스크(#128)를 처리하기 애매해서 진행하지 않았습니다. 다음 우선순위 태스크로 진행할게요!
- 터미널 리사이징이 가능하다.
- 코드 관련 폰트 classname 스타일에 font-size가 지정이 안되어있어서 13px (기존 크기) 로 지정했는데 괜찮을까요?
=> [FE] feat#120 터미널 Resizable Split View 적용

packages/backend/src/common/util.ts, packages/backend/src/quiz-wizard/magic.ts, packages/backend/src/quiz-wizard/quiz-wizard.service.ts, packages/backend/src/ssh/ssh.service.ts, packages/backend/test/app.e2e-spec.ts
close #153 
- 13번 문제 테스트 케이스 작성
- 7번 문제 테스트 케이스 업데이트
- 잘 풀고 마지막에 브랜치만 바꾸는 경우 추가(이것도 정답)
- 커밋 메시지로 커밋 해시 찾을 때 브랜치 명시하도록 변경(없으면 현재 브랜치 기준이라 잘못 채점 가능)
- 13번 문제 채점 로직 구현
- 없습니다.
- 13번 문제 채점 가능
- 없습니다!
=> [BE] feat#153 13번 문제 채점 로직 구현

packages/backend/src/quiz-wizard/quiz-wizard.service.ts, packages/backend/test/app.e2e-spec.ts
close #146 
- 17번 문제 origin, upstream 포함하여 container 서버에 구현
- 17번 문제 채점 테스트 케이스 작성
- 17번 문제 채점 로직 구현
- 없습니다.
- 17번 문제 채점 가능
- 모든 테스트케이스 통과
- 없습니다!
=> [BE] feat#146 17번 문제 채점 로직 구현

packages/backend/src/containers/containers.service.ts, packages/backend/src/quiz-wizard/magic.ts, packages/backend/src/quiz-wizard/quiz-wizard.service.ts, packages/backend/test/app.e2e-spec.ts
close #144 
- 18번 문제 작성
- 18번 문제 컨테이너 서버에 구현
- 18번 문제 채점 테스트 케이스 작성
- 18번 문제 채점 로직 구현
- 없습니다!
- 18번 문제 채점 가능
- 없습니다!
=> [BE] feat#144 18번 문제 채점 로직 구현

packages/frontend/jest.config.mjs, packages/frontend/package.json, yarn.lock
close #216 
- @vanilla-extract/jest-transform  추가 및 설정
cf. Next.js 기본 동작 때문에 설정하는데 오래 걸렸습니다..! 자세한 내용은 [노션 개발 위키](https://www.notion.so/Next-js-Jest-Vanilla-extract-7f24b3e7426a4e869bd59808849e013f)에 작성했습니다!
**객체 형태의 vanilla-extract import 문이 있어도 테스트가 성공하며 변환된 클래스 이름이 할당됨**
|테스트용 코드|테스트 결과|
|-|-|
|<img width="761" alt="image" src="https://github.com/boostcampwm2023/web01-GitChallenge/assets/96400112/f415f232-aa9a-449f-af0c-9aca078e6805">|<img width="1100" alt="image-20231204004315622" src="https://github.com/boostcampwm2023/web01-GitChallenge/assets/96400112/159d89d6-44a2-404c-ace9-d3df5048e1d4">|
**.css 파일을 import 해도 테스트가 성공함**
|테스트용 코드|테스트 결과|
|-|-|
|<img width="685" alt="image" src="https://github.com/boostcampwm2023/web01-GitChallenge/assets/96400112/83f79f70-0738-4938-b534-fd09d22da43 …
=> [FE] config#216 테스트 환경에서 vanilla extract 변환 설정 추가

packages/frontend/src/design-system/tokens/layout.css.ts, packages/frontend/src/pages/quizzes/quiz.css.ts
close #220
- 리사이즈가 가능함을 표시한다.
- 리사이즈를 최상단까지 하면 헤더를 침범합니다..! 헤더랑 리사이즈 표시에 `z-index`를 설정하면 아래처럼 가려지는데 어떻게 할까요? 저는 가려지는 게 좋은 것 같아요!
- #219 작업하려면 리사이즈 바 스타일을 터미널이랑 편집기 각각 줘야할 것 같아요..! 아니면 편집기 모드일 때 폴더 경로랑 명령어를 리사이즈 바에 넣어야 돼요🥹
- 사용자가 리사이즈가 가능함을 알 수 있다.
- 없습니다!
=> [FE] style#220 리사이징 바 표시

packages/backend/src/quizzes/dto/shared.dto.ts, packages/backend/src/quizzes/quizzes.controller.ts, packages/backend/test/api.e2e-spec.ts
close #161 
- shared DTO 선언
- shared API에 대한 e2e 테스트 코드 작성
- shared API 구현
- swagger 선언
- shared.dto.ts에 있는 Decrypted라는 클래스가 있는데, 저희 내부적으로 복호화된 객체를 다루는 클래스입니다. id가 스트링인데, 이는 json으로 압축할 때 stringify 써서 string으로 하는 편이 꽤 유리합니다.
- 400 에러가 추가됐는데, 복호화 실패나 복호화된 값이 이상할 때입니다.
- shared api 사용 가능
- 테스트 코드 통과
- 없습니다!
=> [BE] feat#161 shared API 구현

packages/backend/src/quiz-wizard/quiz-wizard.service.ts, packages/backend/src/quizzes/quizzes.controller.ts
close #262 
- 6번 문제 채점 로직 구현
- dev 브랜치 커밋 헤드 트리 해쉬 확인
- 현재 main브랜치인지 확인
- 문제 정답 시 git 에 앞 뒤로 백틱 추가
- 없습니다!
- 6번 문제 채점 가능
- 없습니다!
=> [BE] feat#262 누락된 6번 문제 채점 로직 구현

packages/frontend/src/design-system/components/common/Header/Header.css.ts, packages/frontend/src/design-system/components/common/Header/Header.tsx, packages/frontend/src/design-system/components/common/Theme/ThemeContext.ts, packages/frontend/src/design-system/components/common/Theme/ThemeSelect.css.ts, packages/frontend/src/design-system/components/common/Theme/ThemeSelect.tsx, packages/frontend/src/design-system/components/common/Theme/ThemeWrapper.tsx, packages/frontend/src/hooks/useTheme.ts, packages/frontend/src/pages/_app.page.tsx
close #179 
- 라이트 모드/다크 모드 전환용 ThemeProvider, useTheme 구현
- 로컬 스토리지에 테마가 없는 경우
없습니다!
- 테마를 변경할 수 있다.
- 조금 급하게 구현해서 코드가 읽기 어려울 수도 있습니다.. ㅠㅠ 편하게 질문/피드백 주세요!
=> [FE] feat#179 다크 모드 지원

packages/backend/src/containers/containers.service.ts, packages/backend/src/quizzes/quizzes.controller.ts
close #285
- stash, stashpop 등 복구 로직 삭제
- quizzer에 대해서 defaultbranch가 master이던 버그 수정
- --global 설정이 일관적으로 사용되도록 적용
- && 버그 수정
- 현재 "" 관련 버그 있어요. 다음 PR 때 수정할 계획입니다. (git commit -m "입력1 입력2" 하면 ""파싱 때문인지 입력1만 커밋 메시지로 인정됨) sh -c 와 관련 있을 것으로 예상합니다.
- 모든 테스트 케이스 통과 (""케이스 제외)
- 복구 로직 삭제해도 기능 작동
- 없습니다!
=> [BE] fix#285 editor 시 컨테이너 복구하는 로직 삭제

packages/frontend/src/components/editor/Editor.css.ts, packages/frontend/src/components/editor/Editor.tsx, packages/frontend/src/components/quiz/SolvedModal/SolvedModal.tsx, packages/frontend/src/pages/quizzes/[id].page.tsx, packages/frontend/src/pages/quizzes/quiz.css.ts, packages/frontend/src/utils/classList.ts
close #219 
- 상단 바에 편집기를 연 명령어와 vi 텍스트 표시
- 편집기 에러 메시지 색상 표시
|light|dark|
|-|-|
|<img width="1043" alt="image" src="https://github.com/boostcampwm2023/web01-GitChallenge/assets/96400112/417b04e4-8a6d-4274-8125-b85787a46cfd">|<img width="1041" alt="image" src="https://github.com/boostcampwm2023/web01-GitChallenge/assets/96400112/58e14e62-19b3-441b-8b9e-38a6faf80bd4">|
- 상단 바에 표시되는 텍스트와 에러 메시지 스타일링이 실제 vi 와 다릅니다. 
- 원래 상단 바에 "폴더 경로 - 명령어 - vi - vi를 실행한 명령어" 로 표시되는데, 폴더 이동 명령어를 지원하지 않아서 안 보여줘도 될 것 같고 "vi - vi를 실행한 명령어" 만으로 충분한 것 같아 다르게 했습니다.
- vi 처럼 배경색을 빨갛게 하면, 아래처럼 텍스트 너비만큼이 아닌 Editor > input 요소 너비만큼 채워져서 에러 느낌이 너무 강합니다..
|vi|vi처럼 에러 메시지 스타일링|
|-|-|
|<img width="677" alt="image" src="https://github.com/boostcampwm2023/web01-GitChallenge/assets/96400112/c19cc39b-e71f-45f0-b61e-2c129f49b0a6"> …
=> [FE] feat#219 편집기 vi처럼 보이게 변경

packages/frontend/src/apis/session.ts, packages/frontend/src/constants/path.ts, packages/frontend/src/contexts/UserQuizStatusContext/UserQuizStatusContext.tsx, packages/frontend/src/contexts/UserQuizStatusContext/index.ts, packages/frontend/src/contexts/UserQuizStatusContext/type.ts, packages/frontend/src/design-system/components/common/SideBar/SideBar.css.ts, packages/frontend/src/design-system/components/common/SideBar/SideBar.tsx, packages/frontend/src/pages/_app.page.tsx, packages/frontend/src/pages/quizzes/[id].page.tsx, packages/frontend/src/types/user.ts
close #252
- 사용자 정답 기록 context 구현
- 사이드바에 맞춘 문제 표시
- 문제 초기화/채점 API 응답에 맞게 사용자 정답 기록 context 업데이트 
**문제 채점 > 문제 초기화 > 문제 채점 > 새로고침 순으로 테스트**
- 새로고침하면 이미 사이드바가 렌더링된 상태(SSG)에서 정답 기록 조회 API 를 요청하기 때문에 한박자 느리게 표시됩니다..
- Sidebar > SubTitleList 에서 사용자 정답 기록 context를 사용하고 있습니다. context가 변경되면 SubTitleList가 모두 렌더링되길래 `React.memo`로 메모이제이션 해봤는데 렌더링 시간 차이가 1ms 이하이길래 제거했습니다..! (아래 그림은 각각 1번 문제를 맞춘 상태에서 초기화했을 때 profile 결과입니다.)
|메모이제이션 전|메모이제이션 후|
|-|-|
|![image](https://github.com/boostcampwm2023/web01-GitChallenge/assets/96400112/da4dc546-ba4e-4f9b-bab3-9781444d3c30)|![image](https://github.com/boostcampwm2023/web01-GitChallenge/assets/96400112/fa0925bc-a8e9-4191-8c25-5423d2ed5e3f)|
- 사용자는 사이드바에서 체크 표시로 자신이 맞춘 문제를 확인할 수 있다.
- 맞춘 문제를 초기화하면 사이드바에서 체크 표시가 사라진다.
- 문제를 맞추면 사이드바에서 체크 표시가 생긴다.
- 변수명이 너무 …
=> [FE] feat#252 사용자 정답 기록 상태 관리

packages/frontend/src/components/graph/Graph.tsx, packages/frontend/src/components/graph/renderTooltip.ts, packages/frontend/src/pages/_app.page.tsx, packages/frontend/src/pages/_document.page.tsx
close #254 
- 기존 텍스트 노드 삭제 후 툴팁 추가
- 그래프 circle 노드에 hover시에 툴팁으로 커밋 해시, 커밋 메시지 안내
- tspan 요소의 텍스트 너비(tspan이라 길이 아니고 너비에요! 한글이랑 영어랑 길이가 달라요)가 정해진 길이를 넘어가면 자르고 말줄임을 추가하도록 구현
- circle 노드에 커서 포인터 설정
- 툴팁, circle에서 툴팁으로 가는 경로에 hover하면 꺼지지 않도록, 그리고 요소에 mouseout되면 꺼지도록 구현
이게 가장 큰 어려움이였는데, 툴팁으로 가는 경로에 투명한 rect svg 요소를 넣어서 해결할 수 있었습니다! 
(테스트용으로 border 처리해놓은 rect입니다)
그리고 노드 자체에 mouseout 이벤트를 넣어 노드가 호버된게 아니라면 툴팁을 지우도록 구현하였습니다!
```typescript
svg.select("#node").on("mouseout", (event) => {
const nodeNotHovered = !(
event.relatedTarget.nodeName === "rect" ||
event.relatedTarget.nodeName === "tspan"
);
if (nodeNotHovered) {
svg.select("#tooltip").remove();
}
});
```
|기존|1차 구현|2차 구현 (UX 개선)|
|-|-|-|
|<img width="700" alt="image" src="https://github.com/boostcampwm2023/web01-GitChallenge/assets/79246447/9e …
=> [FE] feat#254 그래프 hover시에 툴팁으로 커밋 정보 안내, UX 개선

packages/frontend/src/apis/quiz.ts, packages/frontend/src/components/terminal/CommandInput.tsx, packages/frontend/src/components/terminal/Prompt.css.ts, packages/frontend/src/components/terminal/Prompt.tsx, packages/frontend/src/components/terminal/Terminal.css.ts, packages/frontend/src/components/terminal/Terminal.tsx, packages/frontend/src/components/terminal/TerminalContent.tsx, packages/frontend/src/pages/quizzes/[id].page.tsx, packages/frontend/src/reducers/terminalReducer/index.ts, packages/frontend/src/reducers/terminalReducer/terminalReducer.ts, packages/frontend/src/reducers/terminalReducer/type.ts, packages/frontend/src/reducers/terminalReducer/util.ts, packages/frontend/src/types/quiz.ts, packages/frontend/src/types/terminalType.ts, packages/frontend/src/utils/refObject.ts
close #279 
- 터미널에 사용자 이름과 git ref 표시
- 명령어 입력, 그래프 조회 API 응답 타입에 ref 필드 추가
- terminalReducer.ts 코드가 복잡해져 유틸 함수, 타입 분리
- 터미널에 명령어 입력할 때 한글을 작성하고 Enter를 누르면 콜백 함수가 2번 호출되는 버그 수정
- `CommandInput` 클릭 가능한 영역 확장
- 스타일링 변경으로 터미널에 포커싱하기 힘들어졌습니다. gitRef를 추가하면서 `Prompt` 너비가 가변적이라, `Prompt`와 출력값 모두 `inline` 으로 변경했습니다. 그런데 `inline`이다 보니 `width`를 적용할 수 없어 아래처럼 명령어를 입력할 수 있는 `CommandInput` 너비가 0이 됩니다. 이때 사용자가 터미널에 포커싱하기 조금 힘들어졌습니다. 그래서 `CommandInput` 부모 영역을 클릭하면 `CommandInput`에 포커스되도록 변경했습니다.
|AS-IS|TO-BE|
|-|-|
|<img width="945" alt="image" src="https://github.com/boostcampwm2023/web01-GitChallenge/assets/96400112/049027b2-a1dc-4f5d-b5f8-171ba6d1d868">|<img width="943" alt="image" src="https://github.com/boostcampwm2023/web01-GitChallenge/assets/96400112/a65cf5ad-43d7-4082-b603-0223a496e9ab">|
- …
=> [FE] feat#279 터미널에 사용자 이름과 git ref 표시

packages/backend/src/containers/containers.service.ts, packages/backend/src/session/session.service.ts
close #295
- git command 실행 시에는 sh -c 사용하지 않아서 큰따옴표 이용 가능
- isReseted 실행할 때 문제를 못 찾으면 한 번도 안 푼 문제인 거라서 true 리턴
- 아까 코드리뷰 제대로 못 한 것 같아서 너무 아쉽네요. 마음만 급했나 봐요.
- 큰따옴표 입력은 테스트 코드와 postman으로 확인
- 500에러 버그 픽스
- 없습니다!
=> [BE} feat#295 큰따옴표 문제 해결 및 graph 관련 500 에러 버그 픽스

packages/backend/monitoring/docker-compose.monitoring.yml, packages/backend/src/containers/containers.service.ts
close #306 
- git-challenge 서버, container 서버 각각에 cAdvisor(도커 모니터링 익스포터), node exporter 설치
- git-challenge 서버에 docker compose 이용해서 prometheus, grafana, cAdvisor 배포
- ACG설정
- git-challenge 서버로만 3000, 8080, 8081이 적용되도록 변경
- 테스트 용도로 박용준 집에서만 9090포트 접속 가능(prometheus)
- 5000 포트를 통해 [grafana](http://49.50.167.71:5000) 접속 가능
- container 서버에 도커 모니터링을 위해서 cAdvisor 가 도커 컨테이너 형태로 배포돠어야 함
=> 기존 컨테이너 전체 삭제 로직 하면 모니터링도 안 됨
=> git 환경 제공하는 컨테이너에 `git`이라는 라벨을, cAdvisor에는 `monitoring`이라는 라벨을 부착해서 삭제 시 필터링
- docker compose yml은 공개 가능해서 여기다 올리지만, prometheus.yml파일은 비밀이 가득하므로 리포지토리에는 안 올렸어요. 직접 들어가서 보셔도 됩니다~
- 그리고 폴더 구조도 조금 고민이었는데, 일단 제가 작업하는 거니까 backend 안에 놓아 봤어요~
- 그라파나 대시보드
- node_exporter, cAdvisor각각에 대해 가장 유명한 대시보드 가져다 둔 상태이고, 차후에 커스텀 대시보드 제작 예정~
- 없습니다. 오늘은 설치 정도만 해 두고, 커스텀 대시보드나 알람 설정 추가해 볼게요~
- 아직 시간 …
=> [BE] feat#306 모니터링 스택 설치

packages/backend/monitoring/Git-Challenge Dashboard.json
close #308 
- node exporter(리눅스 시스템 모니터링), blackbox exporter(HTTP 모니터링), cAdvisor(컨테이너 상태 모니터링) 세 가지 exporter 기반으로 커스텀 대시보드 작성
- 각 exporter별로 상세 파악을 위한 대시보드 import(유명한 거 가져왔어요)
- 그라파나 Json의 경우 내용을 보실 필요는 없고, 아카이빙 느낌으로 레포지토리에 저장한다고 보시면 됩니다~
[대시보드 설명 링크](https://bow-snail-89d.notion.site/Git-Challenge-cebc6eccb1564655a5401df1c490b0e1?pvs=4)  
이 링크(우리 개발 위키)에 대시보드 설명 적어 뒀어요~
우리 대시보드 너무 예쁘죠?
- 사실 제가 그라파나 대시보드 작업한 과정을 문서화하기보단 차라리 어떻게 쓰는 건지, 어떤 의미를 가지는 값인지 설명하는 쪽이 낫다는 생각이 듭니다... 처음부터 다 정리하기엔 양이 너무 많아요(exporter 3가지 -> prometheus -> grafana 이런 흐름을 설명하기엔...)
- 🎄크리스마스엔 대시보드 꾸미기가 최고~ 🎅
- 대시보드를 통해 서버 상태 관측 가능
- 없습니다!
=> [BE] feat#308 그라파나 대시보드 작성

packages/backend/monitoring/alert.rules.yml, packages/backend/monitoring/alertmanager.yml, packages/backend/monitoring/blackbox.yml, packages/backend/monitoring/docker-compose.monitoring.yml, packages/backend/monitoring/prometheus.yml
close #309 
- 메인 서버에서 컨테이너 서버로 모니터링 스택 이전
- alertmanager 추가 배포
- blackbox exporter 추가 배포
- 알람 템플릿 작성
- 알람 슬랙 연동
- 알람 규칙 작성 및 테스트
알람 규칙 설명은 [개발 위키](https://bow-snail-89d.notion.site/c2bf3eb1bb1949a292a96bf81147c692?pvs=4)에 적어 둡니다~
이런 느낌으로 알람이 와요 (우리 #monitoring 채널 가입하시면 알람 받을 수 있어요)
- yml 파일들은 아카이빙 느낌으로 레포지토리에 옮겼습니다. 실제 모니터링에 사용되는 시크릿들(slack hook api, 서버 IP/Port)은 그냥 your~~~로 마스킹했어요
- 서버 장애 발생 시 webhook 통해 slack 알람 받을 수 있음
- 없습니다!
=> [BE] feat#309 시스템 장애 알람 설정

packages/frontend/src/apis/quiz.ts, packages/frontend/src/apis/session.ts, packages/frontend/src/design-system/components/common/SideBar/GitHelpAccordion.tsx, packages/frontend/src/design-system/components/common/SideBar/SideBar.css.ts, packages/frontend/src/design-system/components/common/SideBar/SideBar.tsx, packages/frontend/src/design-system/tokens/layout.css.ts
close #13 
- 사이드바 하단 버튼으로 문제 상태 전체 초기화 구현
없습니다!
- 문제 상태 전체 초기화 버튼을 누르면 세션이 지워짐
- 사이드바 상태가 초기값으로 변경됨
없습니다!
=> [FE] feat#13 문제 상태 전체 초기화 구현
