boostcampwm2023/web01-GitChallenge

- packages/backend/.gitignore
- packages/backend/package.json
- packages/backend/src/app.module.ts
- packages/backend/src/containers/containers.module.ts
- packages/backend/src/containers/containers.service.spec.ts
- packages/backend/src/containers/containers.service.ts
- packages/backend/src/quizzes/dto/command-request.dto.ts
- packages/backend/src/quizzes/dto/command-response.dto.ts
- packages/backend/src/quizzes/quizzes.controller.ts
- packages/backend/src/quizzes/quizzes.module.ts
- packages/backend/src/quizzes/quizzes.service.ts
- yarn.lock
> Feature be #7

- packages/frontend/.prettierrc
close #76 
- .prettierrc 추가
- 없습니다!
- .prettierrc 설정에 맞게 코드 포맷팅이 된다.
- 없습니다!
> [FE] config#76 prettier 설정

- .gitignore
- .husky/pre-commit
- packages/backend/package.json
- yarn.lock
close #88 
- lint-staged 세팅
없습니다!
- 커밋했을 때 lint에 어긋나는 코드가 있으면 커밋이 안된다.
- prettier가 적용되지 않은 파일을 커밋했을 때 적용된 상태로 커밋이 올라간다.
없습니다!
> [BE] config#88 lint-staged 설정

- .github/workflows/backend-deploy.yml
- packages/backend/.dockerignore
- packages/backend/Dockerfile
close #90
- .github/workflows/backend-deploy.yml 작성
- packages/backend/Dockerfile 작성
- .dockerignore 파일 작성
- 브랜치 push 특성 상 아직 dev-be에서 테스트된 적은 없습니다.
- 자동 배포 테스트
- 도커 이미지 빌드 및 push 완료
- 도커 이미지에 secret 정보가 포함되지 않음
- 없습니다!
> [BE] config#90 백엔드 Github Action 자동 배포 설정

- packages/backend/src/quizzes/dto/quizzes.dto.ts
- packages/backend/src/quizzes/quizzes.service.ts
close #103 
- dto 생성시 정렬코드 추가
- 문제 리스트가 id로 정렬되어 응답된다
> [BE] feat#103 문제 리스트가 id로 정렬되어 응답된다

- packages/backend/src/main.ts
close #107 
- 쿠키 헤더 추가했어요.
- 제발성공
> [BE] config#107 cookie CORS 추가

- packages/backend/src/main.ts
This reverts commit 519a9dc365606c00a02850adafc28c723b8c7f44.
- FE 테스트로 revert 합니다...
> [BE] Revert 108 hotfix be

- .github/workflows/frontend-deploy.yml
close #112 
- "" 문자열을 제대로 고쳤습니다.
- 복사 붙여넣기 할 때 더 주의하겠습니다.
- dev-fe push되면 자동 배포 시작
- 죄송합니다 ㅠㅠ
> [FE] fix#112 "" 문자열 에러 해결

- packages/frontend/src/constants/path.ts
- packages/frontend/src/design-system/components/common/SideBar/GitHelpAccordian.tsx
- packages/frontend/src/design-system/components/common/SideBar/SideBar.css.ts
- packages/frontend/src/design-system/components/common/SideBar/SideBar.tsx
- packages/frontend/src/design-system/components/common/SideBar/nav.ts
close #1 
- 문제 목차 id값으로 `quizzes/[id]` 라우팅 처리
해당 없음
해당 없음
- 문제 목차 데이터는 프론트엔드 정적 데이터로 관리한다
- 목차를 누르면 해당 문제 페이지로 이동한다
- 현재 페이지인 목차에는 볼드 처리가 된다
페어 프로그래밍 했습니당 ✌🏻
> [FE] feat#1 사이드바 컴포넌트 동적 기능 구현

- .github/workflows/backend-deploy.yml
- packages/backend/src/containers/containers.service.ts
close #134 
- mergemasters/alpine-git 0.2 버전 제작
- 새로운 유저 생성
- 유저 디렉터리 생성
- restricted-shell 작성
- /etc/passwd 수정
- 바뀐 디렉터리에 맞추어 로직 수정
- 사실 아직 파이프나 세미콜론 등으로 들어오는 로직은 못 막아요
- mergemasters/alpine-git:0.2 배포
- 0.2에 맞추어 코드 수정
- 로컬 동작 테스트 확인 완료
- 없습니다~
> [BE] 새로운 컨테이너 이미지 제작 및 해당 이미지에 맞추어 코드 수정

- packages/backend/src/quiz-wizard/tests/1.spec.ts
close #141
- 1.spec.ts add
- 1번 채점이 가능하다
> [BE]feat#141 1번 채점이 가능하다

- packages/backend/src/quiz-wizard/tests/2.spec.ts
close #143 
- 2.spec.ts add
- 2번 문제를 채점할 수 있다
> [BE]feat#143 2번 문제를 채점할 수 있다

- packages/backend/src/app.module.ts
- packages/backend/src/containers/containers.module.ts
- packages/backend/src/containers/containers.service.ts
- packages/backend/src/ssh/ssh.connection-pool.service.ts
- packages/backend/src/ssh/ssh.module.ts
- packages/backend/src/ssh/ssh.service.spec.ts
- packages/backend/src/ssh/ssh.service.ts
close #174 
- SSH connection pool service 구현
- SSH service 구현
- 서버 생성 시 초기화 로직 구현
- 서버 시작한 뒤 SSH 연결을 시작하기 때문에 서버시작하자마자 연결하면 느릴 수도 있어요.
- 여전이 첫 연결이 한 0.2~0.3초쯤 느린데, 그 원인은 모르겠습니다. 아예 SSH 처음부터 하는 속도는 아니었어요.
- SSH가 서비스로 분리되어 사용됨
- 속도 향상(SSH 연결을 미리 한 만큼)
- 일단 실행 테스트까진 해 봤는데, 브랜치가 조금 더러운 상태이긴 해요
> [BE] perf#174 SSH connection pool 구현

- packages/frontend/src/components/editor/Editor.tsx
- packages/frontend/src/components/editor/__tests__/editor.spec.tsx
close #184 
- 멘토링 내용 반영
없습니다!
- 모든 테스트 케이스가 통과한다.
없습니다!
> [FE] refactor#184 편집기 컴포넌트 테스트 코드 리팩터링

- .github/workflows/backend-deploy.yml
close #194 
핫픽스 바로 머지합니다.
- CONTAINER_GIT_USERNAME 수정
> [BE] fix#194 CONTAINER_GIT_USERNAME 수정

- packages/frontend/src/components/editor/__tests__/editor.spec.tsx
close #198
- ESLint 에러 해결
**테스트 케이스 통과**
**Next.js 빌드 성공**
- 테스트 케이스 모두 통과
- next build 성공
- ESLint 에러가 있었는데 왜 커밋이 됐을까요..?
> [FE] hotfix#198 ESLint 에러

- packages/backend/src/quiz-wizard/magic.ts
- packages/backend/src/quiz-wizard/quiz-wizard.service.ts
- packages/backend/test/app.e2e-spec.ts
close #154 
- 12번 문제 테스트 코드 작성
- 12번 문제 구현 로직 작성
- feat/somethingB 최신 커밋 트리 해시 비교
- main 최신 커밋 트리 해시 비교
- hotfix/fixA 최신 커밋 트리 해시 비교
git만으로는 파일 생성하고 커밋하기가 어렵기 때문에 각 브랜치별 최신 커밋 보도록 했는데요,
empty 커밋(--allow-empty 옵션) 보내더라도 파일 생성이 안 되면 트리 해시는 같을 거라서 상관 없습니다.
- 없습니다!
- 12번 문제 채점 가능
- 모든 테스트 통과
- 없습니다!
> [BE] feat#154 12번 문제 채점 로직 구현

- packages/backend/src/quiz-wizard/magic.ts
- packages/backend/src/quiz-wizard/quiz-wizard.service.ts
- packages/backend/test/app.e2e-spec.ts
close #142 
- 19번 문제 채점 테스트 케이스 작성
- 19번 문제 채점 로직 작성
- 없습니다!
- 19번 문제 채점 가능
- 없습니다!
> [BE] feat#142 19번 문제 채점 로직 구현

- packages/backend/src/quiz-wizard/magic.ts
- packages/backend/src/quiz-wizard/quiz-wizard.service.ts
- packages/backend/test/app.e2e-spec.ts
close #156 
- 11번 문제 컨테이너에 구현
- 11번 문제 채점 테스트 케이스 작성
- 11번 문제 채점 로직 구현
- checkCondition 선언 부분 개선
- 없습니다.
- 11번 문제 채점 가능
- 없습니다!
> [BE] feat#156 11번 문제 채점 로직 구현

- packages/backend/git-challenge-quiz.csv
- packages/backend/src/quiz-wizard/quiz-wizard.service.ts
- packages/backend/src/quizzes/dto/quiz.dto.ts
- packages/backend/src/quizzes/entity/quiz.entity.ts
- packages/backend/src/quizzes/quizzes.service.ts
close #9 
- 데이터베이스 엔티티 수정
- 초기 삽입 로직 변경
- dto 변경
- quiz csv 일부 수정
- 약간의 버그 픽스 있습니다!
- 모범답안이 보내진다
> [BE] feat#9 모범답안을 확인할 수 있다

- .github/workflows/backend-deploy.yml
- packages/backend/package.json
- packages/backend/src/ai/ai.controller.spec.ts
- packages/backend/src/ai/ai.controller.ts
- packages/backend/src/ai/ai.module.ts
- packages/backend/src/ai/ai.service.spec.ts
- packages/backend/src/ai/ai.service.ts
- packages/backend/src/ai/dto/ai.dto.ts
- packages/backend/src/app.module.ts
- yarn.lock
close #228 
- CLOVA AI 연동
- timeout이 일단 50초입니다!
- ai에게 질문하면 답변이 온다
- 환경변수만 달리해서 서비스용 배포용 나눌 수 있겠어요!
> [BE] feat#228 AI에게 질문 할 수 있다.

- packages/backend/src/containers/containers.service.ts
close #246 
- 개발 시에만 `SERVER_MODE=dev` .env에 추가하면 컨테이너 풀 없이 작동합니다. 저 문자열만 다른 걸로 바꾸면 컨테이너 풀 사용 가능해요.
- getContainer 시 validating을 한 번 더 해서 불의의 사고(우리가 실수로 컨테이너 지우는 경우 99%)를 예방합니다. 나중에는 빼도 되는 로직이에요.
- 오랜만에 접속한 경우 성능이 조금 나빠져요.
- 없습니다!
- 개발 모드에 따라
- 서비스 동작 확인
- 컨테이너 강제 삭제 시에도 다시 생성하여 제공
- 없습니다!
> [BE] feat#246 서버 모드 별 컨테이너 생성 로직 수정 및 getContainer 시 컨테이너 검사 추가

- packages/backend/src/quizzes/quizzes.controller.ts
- packages/backend/src/quizzes/quizzes.service.ts
- packages/backend/src/session/dto/solved.dto.ts
- packages/backend/src/session/session.controller.ts
- packages/backend/src/session/session.service.ts
close #244 
- 문제 정답시 세션에 기록
- 정답 여부 제공 API
- GET /seseion/solved
- dto를 문제 개수에 따른 반복문으로 생성해서 스웨거에 예시가 미흡하게 명시됨
- 요청은 정상적으로 제시됨 
- 문제들의 정답여부를 제공한다
- 없습니다!!
> [BE] feat#244 이때까지 푼 문제들의 정답 상태를 확인할 수 있다.

- packages/backend/git-challenge-quiz.csv
- packages/backend/src/containers/containers.service.ts
- packages/backend/src/quizzes/quizzes.controller.ts
- packages/backend/src/session/session.service.ts
close #260 
- git commit등 editor 명령어 1차에 안 됨
-문제 다시 풀기 가끔 안 됨
- git 레포지토리 아닐 때 에러 2번나옴
- 엑셀에 새로 만든 문제 반영한거 코드에 반영
- 100번 이상 입력 방어
- 우선 명령어 제한 100입니다!
- 버그가 수정되고 입력제한이 생긴다
- 없습니다!
> [BE] feat#260 버그 수정 및 방어 로직

- packages/backend/src/containers/containers.service.ts
- packages/backend/src/quizzes/quizzes.controller.ts
close #265 
- 컨테이너 삭제 실패시 서버에서 핸들링 하지 않는다
##스크린샷
배포에서 동작하지 않는 세션의 동작이
수정후에는 잘 동작한다
테스트코드 잘 동작합니다
- 문제 초기화가 정상적으로 동작한다
- 없습니다!
> [BE] refactor#265 문제초기화 버그 수정

- packages/backend/src/containers/containers.service.ts
- packages/backend/src/quiz-wizard/quiz-wizard.service.ts
- packages/backend/src/quizzes/quizzes.controller.ts
- packages/backend/src/session/session-save.intercepter.ts
close #272 
- 6번 문제 버그 해결
- stash/pop 처럼 이전 상태 저장
- 없습니다.
- 테스트 케이스 통과
- 이전처럼 동작
- 없습니다.
> [BE] feat#272 컨테이너 editor 명령 받으면 이전에 백업해둔 파일 이용

- packages/backend/git-challenge-quiz.csv
- packages/backend/src/containers/containers.service.ts
- packages/backend/src/quizzes/dto/command-response.dto.ts
- packages/backend/src/quizzes/dto/graph.dto.ts
- packages/backend/src/quizzes/entity/quiz.entity.ts
- packages/backend/src/quizzes/quizzes.controller.ts
- packages/backend/src/quizzes/quizzes.service.ts
- packages/backend/src/session/schema/session.schema.ts
- packages/backend/src/session/session.service.ts
- packages/backend/test/api.e2e-spec.ts
close #287 
- csv 파일에 ref 열 추가
- command, graph 요청에 대한 e2e 테스트 작성
- ref 관련 DTO, Schema 등 업데이트
- DB ref 저장 로직 구현
- ref 조회 및 파싱 로직 구현
- 아직 큰따옴표 버그 해결 못 함...
- 없습니다!
> [BE] feat#287 branch 관련 API 구현

- packages/frontend/src/components/terminal/CommandInput.tsx
- packages/frontend/src/components/terminal/Terminal.tsx
- packages/frontend/src/pages/quizzes/[id].page.tsx
> [FE] hotfix/#297

- .github/workflows/backend-deploy.yml
- packages/backend/src/app.controller.ts
- packages/backend/src/app.module.ts
- packages/backend/src/containers/containers.module.ts
- packages/backend/src/containers/containers.service.ts
close #300 
- 블루 그린 배포 전략 적용
- nginx 서버에 blue/green 확인 및 업데이트 하는 아주 작은 서버 배포
- blue/green에 따라 nginx 포트 설정 및 변경 사항 적용
- 서버 init할 때 새 서버가 사용할 pool 생성한 뒤 기존에 있던 컨테이너들 제거하는 로직 구현
- /api/v1/health/ 로 initializeContsiners 상태에 따라 "OK", "Initializing" 리턴하는 GET api 추가
- 새 서버가 pool 생성할 때까지 위 api를 통해서 상태 체크하는 배포 전략 구현
- 서버 배포 시 docker image prune 실행 후 image pull해오도록 구현
- 블루-그린 적용돼서 불안하기 때문에 getContainer할 때 컨테이너 존재 여부 확인 로직 부활
- 기본 store/ 이하 폴더를 생성하는(컨테이너 이전 상태 저장) 불필요한 로직 제거
- 불필요한 github secrets 제거
1. docker image prune 을 통해서 기존 이미지 용량 삭제
2. docker run ~~ 을 통해서 새로운 서버 시작
3. 새로운 서버에 /api/v1/health 요청을 보내서 container pool 생성할 때까지 기다림
4. 생성 끝나면 기존 container pool들을 지우고, 이전 백엔드 서버도 지움
5. nginx 설정 변경
https://bow-snail-89d.notion.site/Blue-Green-a677401645c04b3ba1fec17a5765a13d?pvs=4
```javascript
const …
```
> [BE] feat#300 블루-그린 배포 전략 구현

- packages/backend/src/common/command.guard.ts
close #313 
- 입력 명령어 추가 제한
- '!', '`'
- 즉각 조치입니다
- 추가적인 조치여부를 판단 하고 실행할 계획입니다
- 명령어가 제한된다
- 없습니다!
> [BE] feat#313 명령어 입력 특수문자 제한
